### PR TITLE
Added Travis Static Check

### PR DESCRIPTION
**Pull request by thandayuthapani**
Have done go fmt to the code and commented out few test cases which had dependency with another module.

### CODE REVIEW

**Comment by tianxiaoliang** [comment]
ok

**Review by wangkirin — CHANGES_REQUESTED** [review]
It seems there are some conflicts , please correct it ,thank you !

**Comment by thandayuthapani** [comment]
Have corrected all the conflicts.

**Review by wangkirin — APPROVED** [review]

**Comment by wangkirin** [comment]
LGTM

**Pull request merged**
